/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_lpuart_edma.h"
#include "fsl_flexcan.h"
#include "fsl_lpspi.h"
#include "fsl_lpspi_edma.h"
#include "fsl_gpio.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA0_DMAMUX_BASEADDR DMAMUX
/* Definition of peripheral ID */
#define LPUART3_PERIPHERAL LPUART3
/* Definition of the clock source frequency */
#define LPUART3_CLOCK_SOURCE 80000000UL
/* LPUART3 eDMA source request. */
#define LPUART3_RX_DMA_REQUEST kDmaRequestMuxLPUART3Rx
/* Selected eDMA channel number. */
#define LPUART3_RX_DMA_CHANNEL 0
/* DMAMUX device that is used for muxing of the request. */
#define LPUART3_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART3_RX_DMA_BASEADDR DMA0
/* LPUART3 eDMA source request. */
#define LPUART3_TX_DMA_REQUEST kDmaRequestMuxLPUART3Tx
/* Selected eDMA channel number. */
#define LPUART3_TX_DMA_CHANNEL 1
/* DMAMUX device that is used for muxing of the request. */
#define LPUART3_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART3_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 80000000UL
/* LPUART1 eDMA source request. */
#define LPUART1_RX_DMA_REQUEST kDmaRequestMuxLPUART1Rx
/* Selected eDMA channel number. */
#define LPUART1_RX_DMA_CHANNEL 2
/* DMAMUX device that is used for muxing of the request. */
#define LPUART1_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART1_RX_DMA_BASEADDR DMA0
/* LPUART1 eDMA source request. */
#define LPUART1_TX_DMA_REQUEST kDmaRequestMuxLPUART1Tx
/* Selected eDMA channel number. */
#define LPUART1_TX_DMA_CHANNEL 3
/* DMAMUX device that is used for muxing of the request. */
#define LPUART1_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPUART1_TX_DMA_BASEADDR DMA0
/* Definition of peripheral ID */
#define CAN3_PERIPHERAL CAN3
/* Definition of the clock source frequency */
#define CAN3_CLOCK_SOURCE 40000000UL
/* CAN3 interrupt vector ID (number). */
#define CAN3_FLEXCAN_IRQN CAN3_IRQn
/* CAN3 interrupt handler identifier. */
#define CAN3_FLEXCAN_IRQHANDLER CAN3_IRQHandler
/* BOARD_InitPeripherals defines for LPSPI3 */
/* Definition of peripheral ID */
#define LPSPI3_PERIPHERAL LPSPI3
/* Definition of clock source */
#define LPSPI3_CLOCK_FREQ 132000000UL
/* LPSPI3 eDMA source request. */
#define LPSPI3_RX_DMA_REQUEST kDmaRequestMuxLPSPI3Rx
/* Selected eDMA channel number. */
#define LPSPI3_RX_DMA_CHANNEL 4
/* DMAMUX device that is used for muxing of the request. */
#define LPSPI3_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define LPSPI3_RX_DMA_BASEADDR DMA0
/* GPIO1 interrupt vector ID (number). */
#define GPIO1_GPIO_COMB_16_31_IRQN GPIO1_Combined_16_31_IRQn
/* GPIO1 interrupt handler identifier. */
#define GPIO1_GPIO_COMB_16_31_IRQHANDLER GPIO1_Combined_16_31_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA0_config;
extern const lpuart_config_t LPUART3_config;
extern edma_handle_t LPUART3_RX_Handle;
extern edma_handle_t LPUART3_TX_Handle;
extern lpuart_edma_handle_t LPUART3_LPUART_eDMA_Handle;
extern const lpuart_config_t LPUART1_config;
extern edma_handle_t LPUART1_RX_Handle;
extern edma_handle_t LPUART1_TX_Handle;
extern lpuart_edma_handle_t LPUART1_LPUART_eDMA_Handle;
extern const flexcan_config_t CAN3_config;
extern flexcan_rx_fifo_config_t CAN3_rx_fifo_config;
extern void * rx_fifo_filter;
extern const lpspi_slave_config_t LPSPI3_config;
extern edma_handle_t LPSPI3_RX_Handle;
extern lpspi_slave_edma_handle_t LPSPI3_handle;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
